config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get :profile, to: "users#show"
  resources :users, only: [:index, :edit, :update]
  root "application#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    return redirect_to new_user_session_path if current_user.nil?
    redirect_to profile_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :avatar, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :avatar, :phone_number])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(current_user.id)
  end

  def edit
    # check admin permission before continuing
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(permit_user_params)
      redirect_to users_path
    else
      render :edit
    end
  end


  private

  def permit_user_params
    params.require(:user).permit(:email, :name, :address, :avatar, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">User profiles</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= action_name == 'show' && controller_name == 'users' ? 'active' : '' %>">
        <%= link_to "Profile", profile_path, class: "nav-link" %>
      </li>
      <% if current_user.is_admin %>
        <li class="nav-item  <%= action_name == 'index' && controller_name == 'users' ? 'active' : '' %>">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item navbar-right ">
        <%= link_to "Logout", destroy_user_session_path, data: {method: :delete}, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solbeg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= render "layouts/navbar" %>
    <% end %>


    <div class="container my-4">
      <% if notice %>
        <div class="alert alert-dark mt-3 notice" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-dark mt-3 flash" role="alert">
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserProfiles</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "layouts/navbar" %>

  <div class="container my-4">
    <% if notice %>
      <div class="alert alert-dark mt-3 notice" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-dark mt-3 flash" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/_user.html.erb
<div class="media my-3 bg-light">
  <div class="media-body my-3 mx-3">
    <h5 class="mt-0 mb-1"><%= user.name %></h5>
    <p><%= mail_to user.email %></p>
    <p>Phone number: <%= user.phone_number %></p>
    <%= user.address %>
  </div>
  <% if user.avatar.attached? %>
    <%= image_tag user.avatar, width: "15%", height: "15%", class: "rounded ml-3 my-3 mx-3" %>
  <% else %>
    <%= image_tag "default-avatar-profile-icon-grey.jpg", width: "15%", height: "15%", class: "rounded-circle ml-3 my-3 mx-3" %>
  <% end %>
</div>

<% if controller_name == 'users' && action_name == 'show' %>
  <%= link_to "Edit", edit_user_registration_path %>
<% else%>
  <%= link_to "Edit", edit_user_path(user) %>
<% end  %>

app/views/users/edit.html.erb
<h2>Edit</h2>

<%#= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
<%= form_for @user do |f| %>
  <div class="field form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :address %><br />
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar, class: "form-control-file" %>
  </div>
  <div class="actions">
    <%= f.submit "Update", class: "btn btn-success" %>
  </div>
<% end %>

<br />

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<ul class="list-unstyled">
  <% @users.each do |user|%>
    <li class="media bg-light mb-3">
      <!-- <img class="mr-3" src="..." alt="Generic placeholder image"> -->
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar, width: "15%", height: "15%", class: "rounded ml-3 my-3 mx-3" %>
      <% else %>
        <%= image_tag "default-avatar-profile-icon-grey.jpg", width: "15%", height: "15%", class: "rounded-circle ml-3 my-3 mx-3" %>
      <% end %>
      <div class="media-body mt-3">
        <h5 class="mt-0 mb-1"><%= user.name %></h5>
        <p><%= mail_to user.email %></p>
        <%= user.address %>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
      </div>
      <span class="mr-3 mt-3">
      <% if controller_name == 'users' && action_name == 'show' %>
        <%= link_to "Edit", edit_user_registration_path %>
      <% else%>
        <%= link_to "Edit", edit_user_path(user) %>
      <% end  %>    
      </span>
      
    </li>
  <% end %>
</ul>
<%#= render partial: "user", collection: @users %>

app/views/users/show.html.erb
<%= render @user %>